name: deploy-prod
on:
  push:
    branches:
      - main

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

  build_app:
    needs:   setup
    runs-on: ubuntu-latest
    steps:

      - name: install dependencies
        run:  yarn install

      - name: build app
        run:  yarn build

  run_tests:
    needs:   build_app
    runs-on: ubuntu-latest
    steps:

      - name: run unit tests
        run:  yarn test:karma

  trigger_deployment:
    needs:   run_tests
    runs-on: ubuntu-latest
    steps:

      - name: Send HTTP request to webhook
        run: >-
          curl -X POST https://deploy.altlab.dev/korp-frontend-prod --fail -d '{ "secret": "${{ secrets.DEPLOY_ALTLAB_PROD }}" }' -H 'Content-Type: application/json'
