name: deploy-dev
on:
  push:
    branches:
      - dev

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: cache Node modules
        uses: actions/cache@v2
        with:
          key:  ${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - name: install dependencies
        if:   steps.cache.outputs.cache-hit != 'true'
        run:  yarn install

      - name: build app
        run:  yarn build

      - name: run unit tests
        run:  yarn test:karma

      - name: Send HTTP request to webhook
        run: >-
          curl -X POST https://deploy.altlab.dev/korp-frontend-dev --fail -d '{ "secret": "${{ secrets.DEPLOY_ALTLAB_DEV }}" }' -H 'Content-Type: application/json'
